/* KHELILI ADRIAN P1612177 
   MOULAY LAKHDAR SARAH p1511065
*/ 

CREATE OR REPLACE FUNCTION TAG_EXIST( tag1 TAGS.tag_id%TYPE)
RETURNS BOOL AS $exst$
DECLARE
	has_rows INTEGER := 0;
BEGIN
	has_rows := (SELECT COUNT(1) FROM TAGS WHERE tag_id = tag1);
	RETURN has_rows >= 1;
END;
$exst$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION TRIGGER_ADD_TAG_FUNC()
RETURNS trigger AS $$
DECLARE
	parent varchar(255);
BEGIN
	IF length(NEW.tag_id) = 1 THEN
		RETURN NEW;
	END IF;
	parent := LEFT(NEW.tag_id, length(NEW.tag_id) - 3);
	IF PARENTOF(parent, NEW.tag_id) AND TAG_EXIST(parent) THEN RETURN NEW; END IF;
	RAISE EXCEPTION 'tag_id % n a pas de parent', NEW.tag_id;

END;
$$ LANGUAGE plpgsql;

DROP TRIGGER TRIGGER_ADD_TAG ON TAGS;
/*Premier Trigger*/
CREATE TRIGGER TRIGGER_ADD_TAG BEFORE INSERT ON TAGS
FOR EACH ROW EXECUTE FUNCTION TRIGGER_ADD_TAG_FUNC();

/*Deuxieme trigger */
CREATE TRIGGER TRIGGER_ADD_OUTCOME AFTER INSERT ON OUTCOMES
FOR EACH ROW EXECUTE PROCEDURE STATISTICS_MEPS();

DELETE FROM TAGS WHERE tag_id = '1.20.08' OR tag_id = '1.90.08';

SELECT * FROM TAGS LIMIT 10;
